# **Grep module**

In [101]:
from yaiv import grep
print(grep.__doc__)


YAIV | yaiv.grep

This module provides text-scraping utilities for extracting (grepping) structural and spectral
information from first-principles calculation outputs. It supports common DFT packages
such as Quantum ESPRESSO and VASP.

The functions in this module perform low-level parsing (i.e., grepping) of data such as:

- Electronic eigenvalues and k-points
- Phonon frequencies and paths
- Lattice vectors and stress tensors
- Number of electrons and total energies
- Fermi level and reciprocal space paths

Supported formats include:
- Quantum ESPRESSO output/input: `pw.x`, `ph.x`, `bands.in`, `projwfc.x`, `matdyn.x`, `.xml`
- VASP output: `OUTCAR`, `EIGENVAL`, `KPOINTS`, `PROCAR`

Functions
---------
electron_num(file)
    Greps the number of electrons from a QE or VASP output file.

lattice(file, alat=False)
    Extracts the lattice vectors from outputs. Optionally in internal units (alat).

fermi(file)
    Extracts the Fermi energy from an output file.

total_energy(file, decompo

---
>*The **documentation** of every function is accesible with the usual **shift + tab** shortcut.*
---

# Examples

In [102]:
from yaiv import grep

### Electrons

In [51]:
nElectrons=grep.electron_num('data/qe/results_scf/Si.scf.pwo')
print(f'Quantum espreesso used {nElectrons} electrons.')
nElectrons=grep.electron_num('data/vasp/RESULTS/OUTCAR_BS')
print(f'VASP used {nElectrons} electrons.')

Quantum espreesso used 8 electrons.
VASP used 8 electrons.


### Lattice

In [52]:
print('Basis used by Quantum espresso')
print(grep.lattice('data/qe/results_scf/Si.scf.pwo'))
print('Basis used by VASP')
print(grep.lattice('data/vasp/RESULTS/OUTCAR'))

Basis used by Quantum espresso
[[0.0 2.7343648234158016 2.7343648234158016] [2.7343648234158016 0.0 2.7343648234158016] [2.7343648234158016 2.7343648234158016 0.0]] angstrom
Basis used by VASP
[[0.0 2.734363998 2.734363998] [2.734363998 0.0 2.734363998] [2.734363998 2.734363998 0.0]] angstrom


### Fermi level

In [53]:
fermi=grep.fermi('data/qe/results_scf/Si.scf.pwo')
print(f'Quantum espreesso\'s fermi level is {fermi}')
fermi=grep.fermi('data/vasp/RESULTS/OUTCAR_SCC')
print(f'VASP\'s fermi level is {fermi}')

Quantum espreesso's fermi level is 6.3627 electron_volt
VASP's fermi level is 6.1723 electron_volt


### Total energy (and energy decomposition)

In [54]:
energy=grep.total_energy('data/qe/results_scf/Si.scf.pwo')
print('Total energy in QE: {energy}')
energy=grep.total_energy('data/vasp/RESULTS/OUTCAR')
print('Total energy in VASP: {energy}')

Total energy in QE: {energy}
Total energy in VASP: {energy}


In [55]:
energy=grep.total_energy('data/qe/results_scf/Si.scf.pwo',decomposition=True)
print(f'Free energy= {energy.F}')
print(f'Internal energy= {energy.U}')
print(f'Entropy contribution= {energy.TS}')
print(f'Single electron energy= {energy.U_one_electron}')
print(f'Hartree energy= {energy.U_hartree}')
print(f'Exchange-correlation energy= {energy.U_xc}')
print(f'Ewald energy= {energy.U_ewald}')

Free energy= -93.77214097 rydberg
Internal energy= -93.76999657 rydberg
Entropy contribution= -0.0021444 rydberg
Single electron energy= 5.73621994 rydberg
Hartree energy= 1.13562264 rydberg
Exchange-correlation energy= -12.81773185 rydberg
Ewald energy= -16.67997833 rydberg


### Stress tensor

In [56]:
print('Stress tensor in QE')
print(grep.stress_tensor('data/qe/results_scf/Si.scf.pwo'))
print()
print('Stress tensor in VASP')
print(grep.stress_tensor('data/vasp/RESULTS/OUTCAR'))

Stress tensor in QE
[[376.7405191442384 0.0 0.0] [0.0 376.7405191442384 0.0] [0.0 0.0 376.7405191442384]] kilobar

Stress tensor in VASP
[[34.82684 0.0 0.0] [0.0 34.82684 0.0] [0.0 0.0 34.82684]] kilobar


/u/51/gutierm2/unix/Software/YAIV/build/__editable__.yaiv-1.0.8-py3-none-any/yaiv/grep.py:772: UserWarning: According to VASP this is kB units, but when comparing to QE it appears to be GPa.
  warnings.warn(


### K-paths

In [57]:
kpath=grep.kpath('data/qe/results_bands/Si.bands.pwi')
print('QE path:', kpath.labels)
print(kpath.path)
print()
kpath=grep.kpath('data/vasp/RESULTS/KPATH')
print('VASP:', kpath.labels)
print(kpath.path)
print()

QE path: ['X', 'W', 'L', 'Gamma', 'X', 'X_1', 'K', 'U', 'Gamma']
[[0.5 0.0 0.5 20.0] [0.5 0.25 0.75 20.0] [0.5 0.5 0.5 20.0] [0.0 0.0 0.0 20.0] [0.5 0.0 0.5 1.0] [0.5 0.5 1.0 20.0] [0.375 0.375 0.75 20.0] [0.125 0.125 0.25 20.0] [0.0 0.0 0.0 1.0]] _2pi / crystal

VASP: ['X', 'W', 'L', 'Gamma', 'X', 'X_1', 'K', 'U', 'Gamma']
[[0.5 0.0 0.5 20.0] [0.5 0.25 0.75 20.0] [0.5 0.5 0.5 20.0] [0.0 0.0 0.0 20.0] [0.5 0.0 0.5 1.0] [0.5 0.5 1.0 20.0] [0.375 0.375 0.75 20.0] [0.125 0.125 0.25 20.0] [0.0 0.0 0.0 1.0]] _2pi / crystal



### Electronic Spectrum

In [58]:
print('Quantum Espresso example:')
E=grep.kpointsEnergies('data/qe/results_bands/Si.bands.pwo')
print(f"Energies, ({E.energies.units}):")
print(f"{E.energies[:3,:4].magnitude}...")
print(f"Kpoints, ({E.kpoints.units}):")
print(f"{E.kpoints[:5].magnitude}...")
print('Weights:')
print(f"{E.weights[:5]}...")

Quantum Espresso example:
Energies, (electron_volt):
[[-1.5082 -1.5082 -1.5082 -1.5082]
 [-1.5071 -1.5071 -1.5071 -1.5071]
 [-1.5038 -1.5038 -1.5038 -1.5038]]...
Kpoints, (_2pi / crystal):
[[0.50000001 0.         0.50000001]
 [0.50000001 0.01250002 0.51250003]
 [0.50000001 0.02499997 0.52499999]
 [0.50000001 0.03749999 0.53750001]
 [0.50000001 0.05000002 0.55000003]]...
Weights:
[0.0070423 0.0070423 0.0070423 0.0070423 0.0070423]...


In [59]:
print('VASP EIGENVAL example:')
E=grep.kpointsEnergies('data/vasp/RESULTS/EIGENVAL')
print(f"Energies, ({E.energies.units}):")
print(f"{E.energies[:3,:4].magnitude}...")
print(f"Kpoints, ({E.kpoints.units}):")
print(f"{E.kpoints[:5].magnitude}...")
print('Weights:')
print(f"{E.weights[:5]}...")

VASP EIGENVAL example:
Energies, (electron_volt):
[[-1.86626  -1.866259  3.089611  3.089627]
 [-1.865252 -1.865251  3.08052   3.080536]
 [-1.862249 -1.862248  3.053846  3.053862]]...
Kpoints, (_2pi / crystal):
[[0.5        0.         0.5       ]
 [0.5        0.01315789 0.5131579 ]
 [0.5        0.02631579 0.5263158 ]
 [0.5        0.03947368 0.5394737 ]
 [0.5        0.05263158 0.5526316 ]]...
Weights:
[0.00714286 0.00714286 0.00714286 0.00714286 0.00714286]...


In [60]:
print('VASP OUTCAR example:')
E=grep.kpointsEnergies('data/vasp/RESULTS/OUTCAR')
print(f"Energies, ({E.energies.units}):")
print(f"{E.energies[:3,:4].magnitude}...")
print(f"Kpoints, ({E.kpoints.units}):")
print(f"{E.kpoints[:5].magnitude}...")
print('Weights:')
print(f"{E.weights[:5]}...")

VASP OUTCAR example:
Energies, (electron_volt):
[[-1.8663 -1.8663  3.0896  3.0896]
 [-1.8653 -1.8653  3.0805  3.0805]
 [-1.8622 -1.8622  3.0538  3.0539]]...
Kpoints, (_2pi / crystal):
[[0.5      0.       0.5     ]
 [0.5      0.013158 0.513158]
 [0.5      0.026316 0.526316]
 [0.5      0.039474 0.539474]
 [0.5      0.052632 0.552632]]...
Weights:
[0.007143 0.007143 0.007143 0.007143 0.007143]...


### Phononic spectrum

In [61]:
print('Quantum Espresso example:')
F=grep.kpointsFrequencies('data/qe/results_matdyn/Si.freq')
print(f"Frequencies ({F.frequencies.units}):")
print(f"{F.frequencies[:3,:4].magnitude}...")
print(f"Kpoints ({F.kpoints.units}):")
print(f"{F.kpoints[:5].magnitude}...")

Quantum Espresso example:
Frequencies (speed_of_light / centimeter):
[[689.1662 689.1662 897.3373 897.3373]
 [689.4236 689.4236 897.1973 897.1973]
 [690.1902 690.1902 896.7837 896.7837]]...
Kpoints (_2pi / alat):
[[0.       0.707107 0.      ]
 [0.017678 0.707107 0.      ]
 [0.035355 0.707107 0.      ]
 [0.053033 0.707107 0.      ]
 [0.070711 0.707107 0.      ]]...


### Projections

In [62]:
print('VASP PROCAR example:')
E=grep.kpointsEnergies('data/vasp/RESULTS/PROCAR')
print('Projections:')
print(E.projections)
print()
print(f'Projections over ion=0 with l=1. Same shape as energies ({E.projections(0,1).shape})')
print(E.projections(ion=0,l=1))

VASP PROCAR example:
Projections:
_OrbitalProjectionContainer(ions=2, l=[0, 1, 2], m=[-l,l], M=0)

Projections over ion=0 with l=1. Same shape as energies ((140, 8))
[[0.047 0.047 0.204 ... 0.038 0.256 0.256]
 [0.047 0.047 0.202 ... 0.038 0.254 0.254]
 [0.046 0.046 0.201 ... 0.041 0.246 0.247]
 ...
 [0.    0.22  0.224 ... 0.16  0.158 0.005]
 [0.    0.225 0.224 ... 0.16  0.159 0.002]
 [0.    0.225 0.225 ... 0.16  0.16  0.   ]]


### Dynamical matrix

#### Basic greping

In [77]:
print("Basic reading of a dynamical matrix file")
print("---------")
dyn=grep.dyn_file('data/qe/results_ph/Si.dyn1')
print(f"q-point: {dyn.q}")
print(f"Atomic elements: {dyn.elements}")
print(f"Atomic masses: {dyn.masses}")
print(f"Atomic positions: {dyn.positions}")
print(f"Crystal lattice: {dyn.lattice}")
print(f"Phonon frequencies: {dyn.freqs}")
print(f"Phonon displacements with shape (modes,nions,3) -> {dyn.displacements.shape}")
print(f"{dyn.displacements}")

Basic reading of a dynamical matrix file
---------
q-point: [0.0 0.0 0.0] _2pi / angstrom
Atomic elements: ['Si', 'Si']
Atomic masses: [25598.36728982817 25598.36728982817] _2m_e
Atomic positions: [[0.0 0.0 0.0] [1.3671819952501831 1.3671819952501831 1.3671819952501831]] angstrom
Crystal lattice: [[0.0 2.734363989726971 2.734363989726971] [2.734363989726971 0.0 2.734363989726971] [2.734363989726971 2.734363989726971 0.0]] angstrom
Phonon frequencies: [334.540452 334.540452 334.540452 975.219733 975.219733 975.219733] speed_of_light / centimeter
Phonon displacements with shape (modes,nions,3) -> (6, 2, 3)
[[[-0.354736+0.j  0.525236+0.j  0.313512+0.j]
  [-0.354736+0.j  0.525236+0.j  0.313512+0.j]]

 [[-0.411101+0.j  0.06365 +0.j -0.571791+0.j]
  [-0.411101+0.j  0.06365 +0.j -0.571791+0.j]]

 [[ 0.452945+0.j  0.469122-0.j -0.273432+0.j]
  [ 0.452945+0.j  0.469122-0.j -0.273432+0.j]]

 [[-0.340761+0.j -0.57196 +0.j -0.23821 +0.j]
  [ 0.340761-0.j  0.57196 -0.j  0.23821 -0.j]]

 [[ 0.607468

#### Full dynamical matrix greping

In [95]:
print(grep.dyn_q.__doc__)


    Reads the Quantum ESPRESSO `.dyn*` file corresponding to a given q-point.

    This function locates the `.dyn*` file generated by `ph.x` that corresponds to a
    desired q-point (in reduced crystalline coordinates), extracts the corresponding dynamical
    matrix, and optionally converts it to the real physical dynamical matrix in units
    of 1 / [time]².

    Parameters
    ----------
    q_cryst : np.ndarray | ureg.Quantity
        The q-point of interest, expressed in reduced crystalline coordinates (fractions of reciprocal lattice vectors).
        If not a `Quantity`, it is assumed to be in `_2pi/crystal` units.

    results_ph_path : str
        Path to the directory containing the Quantum ESPRESSO `ph.x` output `.dyn*` files.

    qe_format : bool, optional
        If True (default), returns the raw QE dynamical matrix (includes sqrt(m_i m_j) mass factors).
        If False, converts the dynamical matrix to true physical form in 1 / [time]² units (Ry/h)^2.

    Returns
 

In [96]:
print("Detailed reading of a dynamical matrix file")
print("---------")
dyn=grep.dyn_q(q_cryst=[0.5,0,0],results_ph_path='data/qe/results_ph/')
print(f"q-point: {dyn.q}")
print(f"Atomic elements: {dyn.elements}")
print(f"Atomic masses: {dyn.masses}")
print(f"Atomic positions: {dyn.positions}")
print(f"Crystal lattice: {dyn.lattice}")
print(f"Full dynamical matrix (3*nions,3*nions) and ({dyn.dyn.units}) units")
print(f"{dyn.dyn.magnitude}")

Detailed reading of a dynamical matrix file
---------
q-point: [0.5 0.0 0.0] _2pi / crystal
Atomic elements: ['Si', 'Si']
Atomic masses: [25598.36728982817 25598.36728982817] _2m_e
Atomic positions: [[0.0 0.0 0.0] [1.3671819952501831 1.3671819952501831 1.3671819952501831]] angstrom
Crystal lattice: [[0.0 2.734363989726971 2.734363989726971] [2.734363989726971 0.0 2.734363989726971] [2.734363989726971 2.734363989726971 0.0]] angstrom
Full dynamical matrix (3*nions,3*nions) and (_2m_e * rydberg ** 2 / planck_constant ** 2) units
[[ 1.58038486+0.j -0.14995245+0.j -0.14995245+0.j -0.49614779+0.j
  -0.1800625 +0.j -0.1800625 +0.j]
 [-0.14995245+0.j  1.58038486+0.j  0.14995245+0.j -0.1800625 +0.j
  -0.49614779+0.j  0.1800625 +0.j]
 [-0.14995245+0.j  0.14995245+0.j  1.58038486+0.j -0.1800625 +0.j
   0.1800625 +0.j -0.49614779+0.j]
 [-0.49614779+0.j -0.1800625 +0.j -0.1800625 +0.j  1.58038486+0.j
  -0.14995245+0.j -0.14995245+0.j]
 [-0.1800625 +0.j -0.49614779+0.j  0.1800625 +0.j -0.14995245+0