In [102]:
import sys

In [105]:
try:
    b = awq * 100
except Exception as e:
    exc_info = sys.exc_info()

In [106]:
exc_info

(NameError,
 NameError("name 'awq' is not defined"),
 <traceback at 0x7b3256164d80>)

In [109]:
tb  = exc_info[-1]

In [111]:
import traceback

In [116]:
traceback.print_tb(tb)

  File "/tmp/ipykernel_26967/4250631686.py", line 2, in <module>
    b = awq * 100


In [117]:
traceback.format_exc()

'NoneType: None\n'

In [1]:

import gymnasium as gym

env = gym.make("LunarLander-v3")


/home/adrian/projects/parallenv/.venv/lib/python3.10/site-packages/pygame/pkgdata.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_stream, resource_exists


In [2]:
ob, info =  env.reset()

In [10]:
env.observation_space

Box([ -2.5        -2.5       -10.        -10.         -6.2831855 -10.
  -0.         -0.       ], [ 2.5        2.5       10.        10.         6.2831855 10.
  1.         1.       ], (8,), float32)

In [9]:
env.action_space.sample()

np.int64(0)

In [52]:
for _ in range(1000):
    ac = env.action_space.sample()
    ob, reward, truncated, terminated, info = env.step(ac)
    if terminated:
        print("finished!!")
        break

finished!!


In [53]:
terminated

True

In [101]:
env.step(env.action_space.sample())

(array([-0.38710436, -0.03292979, -0.00917741, -0.05025944, -0.12206075,
        -0.01582365,  1.        ,  0.        ], dtype=float32),
 -100,
 True,
 True,
 {})

In [18]:

import functools

import gymnasium as gym
from gymnasium import spaces
import numpy as np
from parallenv import ParallEnv

class IdEnv(gym.Env):
    def __init__(self, id: int):
        self.id = id
        self.observation_space = spaces.Box(1, 1)
        self.action_space = spaces.Box(1, 1)

    def step(self, action):
        return np.array((0,)), 0, False, False, {"env_id": self.id}

    def reset(
        self,
        *,
        seed = None,
        options = None,
    ):
        """Resets the environment."""
        super().reset(seed=seed, options=options)
        return  np.array((0,)), {"env_id": self.id}


env_fns = [functools.partial(IdEnv, i) for i in range(4)]

In [20]:
envs = ParallEnv(
    env_fns=env_fns,
    batch_size=4,
    num_workers=4,
)
envs.reset()
print("reseted")
ids, observation, reward, terminated, truncated, info = envs.gather()
envs.close()
print(info["env_id"])



reseted
[1 2 3 0]


True

In [21]:
ids

array([1, 2, 3, 0], dtype=int32)

In [3]:
sepenvs = [f() for f in env_fns]

In [4]:
from gymnasium.vector.utils import batch_space, concatenate, create_empty_array


In [5]:
single_observation_space = sepenvs[0].observation_space

In [6]:

observations = create_empty_array(
    single_observation_space, n=len(sepenvs), fn=np.zeros
)

In [7]:
observations

array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [9]:
sepenvs[0].reset()

(0, {'env_id': 0})

In [10]:
observation_buffer, infos = zip(*[env.reset() for env in sepenvs])

In [11]:
observation_buffer

(0, 0, 0, 0)

In [13]:
observation_buffer

(0, 0, 0, 0)

In [16]:
        observations = concatenate(
            single_observation_space,
            [np.array((v,)) for v in observation_buffer],
            observations,
        )


In [17]:
observations

array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
sepenvs

In [9]:
for fn in fns:
    fn() 

0
1
2
3


In [1]:
import gymnasium as gym



In [5]:
env = gym.make("LunarLander-v3")

In [6]:
env.reset()

(array([ 0.00412579,  1.4051588 ,  0.41787753, -0.2560674 , -0.0047739 ,
        -0.09465547,  0.        ,  0.        ], dtype=float32),
 {})

In [8]:
from gymnasium.vector.utils import batch_space

In [9]:
env.observation_space

Box([ -2.5        -2.5       -10.        -10.         -6.2831855 -10.
  -0.         -0.       ], [ 2.5        2.5       10.        10.         6.2831855 10.
  1.         1.       ], (8,), float32)

In [11]:
batch_space(env.observation_space, 10)

Box([[ -2.5        -2.5       -10.        -10.         -6.2831855 -10.
   -0.         -0.       ]
 [ -2.5        -2.5       -10.        -10.         -6.2831855 -10.
   -0.         -0.       ]
 [ -2.5        -2.5       -10.        -10.         -6.2831855 -10.
   -0.         -0.       ]
 [ -2.5        -2.5       -10.        -10.         -6.2831855 -10.
   -0.         -0.       ]
 [ -2.5        -2.5       -10.        -10.         -6.2831855 -10.
   -0.         -0.       ]
 [ -2.5        -2.5       -10.        -10.         -6.2831855 -10.
   -0.         -0.       ]
 [ -2.5        -2.5       -10.        -10.         -6.2831855 -10.
   -0.         -0.       ]
 [ -2.5        -2.5       -10.        -10.         -6.2831855 -10.
   -0.         -0.       ]
 [ -2.5        -2.5       -10.        -10.         -6.2831855 -10.
   -0.         -0.       ]
 [ -2.5        -2.5       -10.        -10.         -6.2831855 -10.
   -0.         -0.       ]], [[ 2.5        2.5       10.        10.         6.28318

In [8]:
env.observation_space.shape

(8,)

In [2]:
import numpy as np

In [3]:
a = [1,2,3,4,5,56]

In [8]:
mask = [True, False, True, True, False, False]

In [7]:
ar = np.array(a)

In [10]:
ar[mask]

array([1, 3, 4])

In [6]:
isinstance(np.array(a), np.ndarray)

True

In [5]:

isinstance(a, np.ndarray)

False

In [11]:
from collections.abc import Callable, Sequence

In [14]:
isinstance(ar, Sequence)

False

In [15]:
from parallenv import ParallEnv
import gymnasium as gym

env_fns = [lambda: gym.make("LunarLander-v3") for _ in range(32)]

envs = ParallEnv(env_fns, 16, 4)

/home/adrian/projects/parallenv/.venv/lib/python3.10/site-packages/pygame/pkgdata.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_stream, resource_exists


In [35]:
envs.action_space.sample()

array([0, 0, 0, 2, 0, 2, 1, 1, 3, 3, 0, 2, 0, 2, 1, 0])

In [33]:
envs.single_action_space.sample()

np.int64(1)